# Analyze the ramen data

The Ramen Rater is a product review website for the hardcore ramen enthusiast (or "ramenphile"), with over 2500 reviews to date.
This dataset is an export of "The Big List" (of reviews), converted to a CSV format.

https://www.kaggle.com/residentmario/ramen-ratings

In [52]:
# Import pandas package first
import pandas as pd

1. Read the data from the CSV file into a DataFrame

In [53]:
from google.colab import drive
drive.mount('/content/drive')

file = '/content/drive/MyDrive/Python 101/ramen_ratings.csv'
df = pd.read_csv(file)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

2. Display the first five rows of data

In [54]:
df.head(5)

,Brand,Variety,Style,Country,Stars
0,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75
1,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00
2,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25
3,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75
4,Ching's Secret,Singapore Curry,Pack,India,3.75

3. Display the last five rows of data

In [55]:
df.tail(5)

,Brand,Variety,Style,Country,Stars
2572,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5
2573,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1.0
2574,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2.0
2575,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2.0
2576,Westbrae,Miso Ramen,Pack,USA,0.5

4. Display statistical information for the numeric columns.

    describe(): https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html

In [56]:
df.describe()

             Stars
count  2577.000000
mean      3.654676
std       1.015331
min       0.000000
25%       3.250000
50%       3.750000
75%       4.250000
max       5.000000

5. Dislay the number of unique values for each column.

    nunique(): https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.nunique.html

In [57]:
for col in df.columns:
  print(f'{col}\t:{df[col].nunique()}')

Brand	:355
Variety	:2410
Style	:7
Country	:38
Stars	:42

6. Display only rows where the country is Vietnam.

    query(): https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html

In [58]:
df.query('Country == "Vietnam"')

,Brand,Variety,Style,Country,Stars
18,Binh Tay,Mi Hai Cua,Pack,Vietnam,4.00
52,Uni-President,Mushroom Flavor,Pack,Vietnam,0.00
143,Mum Ngon,Lau Tom Chua Cay,Pack,Vietnam,3.50
224,Vifon,Viet Cuisine Bun Rieu Cua Sour Crab Soup Insta...,Bowl,Vietnam,5.00
365,Acecook,Oh! Ricey Pork Flavour,Pack,Vietnam,4.00
...,...,...,...,...,...
2486,Binh Tay,Mi Chay Mushroom,Pack,Vietnam,2.75
2535,Ve Wong,Kung-Fu Chicken Flavor,Pack,Vietnam,2.75
2570,Ve Wong,Mushroom Pork,Pack,Vietnam,1.00
2571,Vifon,Nam Vang,Pack,Vietnam,2.50
2572,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.50

7. Display only the Brand and Style columns

In [59]:
df[['Brand', 'Style']]

               Brand Style
0          New Touch   Cup
1           Just Way  Pack
2             Nissin   Cup
3            Wei Lih  Pack
4     Ching's Secret  Pack
...              ...   ...
2572           Vifon  Bowl
2573         Wai Wai  Pack
2574         Wai Wai  Pack
2575         Wai Wai  Pack
2576        Westbrae  Pack

[2577 rows x 2 columns]

8. Display only the Country column

In [60]:
df[['Country']]

       Country
0        Japan
1       Taiwan
2          USA
3       Taiwan
4        India
...        ...
2572   Vietnam
2573  Thailand
2574  Thailand
2575  Thailand
2576       USA

[2577 rows x 1 columns]

9. Display the data after it has been sorted by the Stars column from high values to low values.
    
    sort_values(): https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html

In [61]:
df.sort_values('Stars', ascending=False)

,Brand,Variety,Style,Country,Stars
2549,Nissin,Chikin Ramen,Pack,Japan,5.0
30,Samyang Foods,Paegaejang Ramen,Pack,South Korea,5.0
10,Tao Kae Noi,Creamy tom Yum Kung Flavour,Pack,Thailand,5.0
11,Yamachan,Yokohama Tonkotsu Shoyu,Pack,USA,5.0
28,MyKuali,Penang White Curry Rice Vermicelli Soup,Bowl,Malaysia,5.0
...,...,...,...,...,...
622,Maruchan,Spicy Tomato Salsa Ramen,Cup,Japan,0.0
937,One Dish Asia,Japanese Ramen Noodle,Bowl,USA,0.0
2534,Kim Ve Wong,Jaopai Series: Vegetarian Instant Noodles,Bowl,Taiwan,0.0
52,Uni-President,Mushroom Flavor,Pack,Vietnam,0.0
475,Roland,Ramen Japanese Style Quick-Cooking Alimentary ...,Pack,USA,0.0

10. In the Country column, replace 'USA' with 'United States'.
    
    replace(): https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.replace.html

In [62]:
df = df.replace('USA', 'United States')
df.head(5)

,Brand,Variety,Style,Country,Stars
0,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75
1,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00
2,Nissin,Cup Noodles Chicken Vegetable,Cup,United States,2.25
3,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75
4,Ching's Secret,Singapore Curry,Pack,India,3.75

### Questions

1. How many countries are represented in the data?

In [63]:
uniq_countries = df['Country'].nunique()
print(f'Unique countries represented in the data: {uniq_countries}')

Unique countries represented in the data: 37

2. Which three countries have the highest average rating?
    
    groupby(): https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html

In [64]:
average = df.groupby("Country")["Stars"].mean()
average.sort_values(ascending=False).head(3)

Country
Brazil      4.350000
Sarawak     4.333333
Cambodia    4.200000
Name: Stars, dtype: float64

3. Which three countries have the lowest average rating?

In [65]:
average.sort_values(ascending=True).head(3)

Country
Nigeria        1.500000
Canada         2.243902
Netherlands    2.483333
Name: Stars, dtype: float64

4. Which three countries have the most brands, and how many brands does each of these countries have?

In [66]:
most_brands = df.groupby("Country")["Brand"].nunique()
most_brands.sort_values(ascending=False).head(3)

Country
Japan            58
United States    49
Taiwan           47
Name: Brand, dtype: int64

End of notebook.